const menuItemsData = [
    {
      id: 1,
      name: 'Summer Asian Slaw',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 15,
      img: 'https://i.ibb.co/CK74ZHB/bowl1.png',
    },
    {
      id: 2,
      name: 'Burger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://i.ibb.co/9bx1GRc/bowl2.png',
    },
    {
      id: 3,
      name: 'White Sauce Pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 18,
      img: 'https://i.ibb.co/8Pqpmts/bowl3.png',
    },
    {
      id: 4,
      name: 'Butterfly Pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 20,
      img: 'https://i.ibb.co/3hKMdfg/bowl4.png',
    },
    {
      id: 5,
      name: 'Tooty Fruity Bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 15,
      img: 'https://i.ibb.co/BgS3B4P/fruits.png',
    },
    {
      id: 6,
      name: 'Granola Cereal Bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 22,
      img: 'https://i.ibb.co/ynTBfnc/granola-cereal-bowl.png',
    },
    {
      id: 7,
      name: 'Palm Bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 19,
      img: 'https://i.ibb.co/8MFcdZW/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07-9992682215299010545066.png',
    },
    {
      id: 8,
      name: 'Tigela Smoothie',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 12,
      img: 'https://i.ibb.co/98nqdJ8/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908-66956303152789462431.png',
    },
    {
      id: 10,
      name: 'Breakfast Cereal',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 10,
      img: 'https://i.ibb.co/KwmWMYp/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69-189189231522830725.png',
    },
    {
      id: 11,
      name: 'Cuisine of Hawaii',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://i.ibb.co/Z8RWVTy/kisspng-cuisine-of-hawaii-l-l-hawaiian-barbecue-shrimp-gam-frozen-chicken-5b1e62f3a9e035-27662824152.png',
    },
    {
      id: 12,
      name: 'Fried Chicken',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 28,
      img: 'https://i.ibb.co/dDYvrsS/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22-82120543151.png',
    },
    {
      id: 13,
      name: 'Greek Salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 17,
      img: 'https://i.ibb.co/bWTrtYB/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3-7299622115198423.png',
    },
    {
      id: 14,
      name: 'Israeli Salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 14,
      img: 'https://i.ibb.co/BGR1FqJ/kisspng-israeli-salad-european-cuisine.png',
    },
    {
      id: 15,
      name: 'Pizza Pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 20,
      img: 'https://i.ibb.co/1K9Gpc3/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7-3892346415222390470077.png',
    },
    {
      id: 16,
      name: 'Pizza',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 30,
      img: 'https://i.ibb.co/m0DNP26/pizza.png',
    },
    {
        id: 17,
        name: 'Mediterranean  Salad',
        info: 'spicey with garlic and then deep fried to crispy perfection',
        price: 24,
        img: 'https://i.ibb.co/8rBmFFF/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41-2676743415176192608466.png',
      }
  ];